/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_khoa_plugin_antiopsec_native_NativeBridge */

#ifndef _Included_dev_khoa_plugin_antiopsec_native_NativeBridge
#define _Included_dev_khoa_plugin_antiopsec_native_NativeBridge
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jboolean JNICALL Java_dev_khoa_plugin_antiopsec_native_NativeBridge_verifyCoreIntegrity
  (JNIEnv *, jclass, jstring);

JNIEXPORT jbyteArray JNICALL Java_dev_khoa_plugin_antiopsec_native_NativeBridge_decryptSignature
  (JNIEnv *, jclass, jbyteArray);

JNIEXPORT jboolean JNICALL Java_dev_khoa_plugin_antiopsec_native_NativeBridge_validateLicense
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
