# ===================================================================
# AUTO-GENERATED ENTERPRISE PROGUARD CONFIG FOR: CookieChess
# Generated by CookieFuscator Master Engine
# ===================================================================

-ignorewarnings
-dontwarn **
-dontshrink
-dontoptimize
-dontusemixedcaseclassnames
-overloadaggressively
-allowaccessmodification

-repackageclasses 'cookie.fack.please.d111'
-keepdirectories
-adaptresourcefilecontents plugin.yml,bungee.yml,velocity-plugin.json

-obfuscationdictionary "E:/SERVER/plugin-pre/Unique/Obf Logic/dictionaries/confusing_dict.txt"
-classobfuscationdictionary "E:/SERVER/plugin-pre/Unique/Obf Logic/dictionaries/confusing_dict.txt"
-packageobfuscationdictionary "E:/SERVER/plugin-pre/Unique/Obf Logic/dictionaries/confusing_dict.txt"

-keepattributes Exceptions,Signature,Deprecated,*Annotation*,EnclosingMethod,InnerClasses

# 1. MAIN ENTRY POINT
-keepclassmembers public class * extends org.bukkit.plugin.java.JavaPlugin {
    public <init>();
    public void onLoad();
    public void onEnable();
    public void onDisable();
}
-keepclassmembers public class * extends net.md_5.bungee.api.plugin.Plugin {
    public <init>();
    public void onLoad();
    public void onEnable();
    public void onDisable();
}
-keep @com.velocitypowered.api.plugin.Plugin class * { *; }

# 2. EVENT LISTENERS
-keepclassmembers class * implements org.bukkit.event.Listener {
    @org.bukkit.event.EventHandler *;
}
-keepclassmembers class * implements net.md_5.bungee.api.plugin.Listener {
    @net.md_5.bungee.event.EventHandler *;
}
-keepclassmembers class * {
    @com.velocitypowered.api.event.Subscribe *;
}

# 3. COMMAND EXECUTORS
-keepclassmembers class * implements org.bukkit.command.CommandExecutor {
    public boolean onCommand(...);
}
-keepclassmembers class * implements org.bukkit.command.TabCompleter {
    public java.util.List onTabComplete(...);
}
-keepclassmembers class * extends net.md_5.bungee.api.plugin.Command {
    public <init>(...);
    public void execute(...);
}

# 4. ENUMS & SERIALIZABLES
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}
-keepclassmembers class * implements java.io.Serializable { *; }

# 5. PLACEHOLDER EXPANSIONS
-keepclassmembers class * extends me.clip.placeholderapi.expansion.PlaceholderExpansion {
    public <init>(...);
    public boolean persist();
    public boolean canRegister();
    public java.lang.String getAuthor();
    public java.lang.String getIdentifier();
    public java.lang.String getVersion();
    public java.lang.String onPlaceholderRequest(...);
    public java.lang.String onRequest(...);
}

# 8. HIKARICP & LOGGERS
-keep class com.zaxxer.hikari.** { *; }
-keep class org.slf4j.** { *; }
-keep class *.libs.hikaricp.** { *; }
-keep class *.*.libs.hikaricp.** { *; }
